(require 'powerline)
(require 'tramp)
;(require 'helm-config)
(require 'mu4e-jump-to-list)
(require 'chruby)
(chruby "ruby-2.5")
(mu4e-alert-enable-notifications)
(projectile-mode +1)
(powerline-reset)
(dumb-jump-mode)
(rainbow-delimiters-mode)
